### ISSUE TITLE
override missing functions in Serializer

### ISSUE THREAD

**Issue by animeshtrivedi** [zrlio/spark-io#1]
spark-io's serializer wrapper does not overload all the functions from the spark deserializer. It should do that, here: 

https://github.com/zrlio/spark-io/blob/master/src/main/scala/org/apache/spark/shuffle/crail/CrailSparkShuffleSerializer.scala#L82

More specifically missing functions are: asKeyValueIterator and asIterator. In absense of that, for example, SQL deserializer code is not called, and instead a slow default implementation is called.

**Comment by patrickstuedi** [comment]
commit 8a455448a4b33f8d5d46445b4421c744a21bda19
